# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_createsu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Benefactors',
        ),
    ]
