# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 11:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_auto_20171114_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefactors',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
