# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0006_userstatus_dead_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15)),
                ('pin', models.CharField(max_length=5)),
            ],
        ),
    ]
