# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0006_userstatus_dead_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=150)),
                ('decision', models.BooleanField()),
            ],
        ),
    ]
