# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 11:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persona', '0007_saveotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefactorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='benefactor_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
