# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0009_merge_20171120_0712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefactor',
            options={'verbose_name': 'Benefactor', 'verbose_name_plural': 'Benefactors'},
        ),
        migrations.AlterModelOptions(
            name='benefactors',
            options={'verbose_name': 'Benefactor user mapping', 'verbose_name_plural': 'Benefactors user mapping'},
        ),
        migrations.AlterModelOptions(
            name='trainingdata',
            options={'verbose_name': 'Training Data', 'verbose_name_plural': 'Training Data'},
        ),
        migrations.AlterModelOptions(
            name='userstatus',
            options={'verbose_name': 'User Status', 'verbose_name_plural': "User's Status"},
        ),
        migrations.AddField(
            model_name='userstatus',
            name='last_activity',
            field=models.TextField(blank=True, null=True),
        ),
    ]
