# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0010_auto_20171120_1213'),
        ('persona', '0009_merge_20171117_1209'),
    ]

    operations = [
    ]
