"""
Django settings for spoutcoin project.

Generated by 'django-admin startproject' using Django 1.8.18.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'd@s-4g1f0rbf1c*$-)_57vvy4g_l%leays^!x^y)4$)tq6tx$c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_cron',
    'persona',
    'social_django',
    'widget_tweaks',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
)

ROOT_URLCONF = 'spoutcoin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

STATIC_URL = '/static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)

WSGI_APPLICATION = 'spoutcoin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
    'persona.pipeline.get_profile_data',
    )

AUTHENTICATION_BACKENDS = (
    'social_core.backends.github.GithubOAuth2',
    'social_core.backends.twitter.TwitterOAuth',
    'social_core.backends.linkedin.LinkedinOAuth',
    'social_core.backends.facebook.FacebookOAuth2',

    'django.contrib.auth.backends.ModelBackend',
)

LOGIN_URL = '/'
LOGIN_REDIRECT_URL = '/'

SOCIAL_AUTH_LOGIN_ERROR_URL = '/'
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/send_otp/'
SOCIAL_AUTH_RAISE_EXCEPTIONS = False

SOCIAL_AUTH_TWITTER_KEY = "upU4B71IOdrCSnaZThkAB4pjT"
SOCIAL_AUTH_TWITTER_SECRET = "GwqVw2oMYHg727bCUpPsFN6anQkUaEngK17GpkhPMq181fQyWM"

SOCIAL_AUTH_LINKEDIN_KEY = '78w8u1kpsetzhk'
SOCIAL_AUTH_LINKEDIN_SECRET = 'YsUb2afkdwar7Ebo'

SOCIAL_AUTH_LINKEDIN_SCOPE = ['r_basicprofile', 'r_emailaddress']
# These fields be requested from linkedin.
SOCIAL_AUTH_LINKEDIN_FIELD_SELECTORS = [
    'email-address',
    'picture-url',
]
SOCIAL_AUTH_LINKEDIN_EXTRA_DATA = [
    ('id', 'id'),
    ('firstName', 'first_name'),
    ('lastName', 'last_name'),
    ('emailAddress', 'email_address'),
    ('public-profile-url', 'public_profile_url'),
]
"""--------------------Twilo settings---------------- """

TWILIO_ACCOUNT_SID = "ACd2b21d150c3d91ce9207b27cf8e00bd2"
TWILIO_AUTH_TOKEN = "70f1dd7dabda5c9ca8c096f238214ed8"
TWILIO_FROM_NUMBER = "(844) 214-8817"
# Email Settings by local

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'test.sarath.techversant@gmail.com'
EMAIL_HOST_PASSWORD = 'techversant!@'

CRON_CLASSES = [
    "persona.cron.UserDead",
]

FACEBOOK_TOKEN = "EAAB0ZAUWVCWcBAOiQTAsoZA2fcdQVcANVawzHZBEtT5QujQQH1yC40nZC2PdKZB7SJ7o7JFvY41JK6I6vUfZBaXtVmYk7rKeaeJu55RLR78ROkSj6BZATZCNjoWMDVQfPm86rZADEFp5uMHZAgPmf2WwzFCC3ElOFUll0uHfZCOnKXqtfVLPZCcUxa21"
# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

TWITTER_CONSUMER_KEY  = "dU1UOgmbDH3Obr7K1JtNUeeBE"
TWITTER_CONSUMER_SECRET = "Ik3DzjyxNyWDNfURvF7QfDmnxTbczdw2PO4PXBAgikyMsNrOw8"
TWITTER_ACCESS_TOKEN = "3257376390-768tA7hK0hoTBMg9MTItjm7kagIvj00C87zfNWi"
TWITTER_ACCESS_TOKEN_SECRET = "qFwlw2A0xnMSUbq9IA7YjSZxdJYtpglnHtW5CcE2yBDA5"

REDDIT_USER = 'sarahraycw'

ACTIVITY_DAYS = 3


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.zoho.com'
EMAIL_PORT = 587

EMAIL_HOST_USER = 'sarahray@flaskmedia.com'
EMAIL_HOST_PASSWORD = '2Uuuu-Deed0-Payne'
#EMAIL_HOST_PASSWORD = 'developer@realtordaddy'
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'sarahray@flaskmedia.com'




LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '%(asctime)s %(levelname)s %(name)s %(message)s'
        },
    },
    'handlers': {
        'default': {
            'level':'DEBUG',
            'class':'logging.handlers.RotatingFileHandler',
            'filename': 'cron.log',
            'maxBytes': 1024*1024*5, # 5 MB
            'backupCount': 5,
            'formatter':'simple',
        },
    },
    'loggers': {
        'sample': {
            'handlers': ['default'],
            'level': 'DEBUG',
            'propagate': True,
        },
    }
}